// svelte-crud/src/routes/auth/login/+page.svelte
<script lang="ts">
	import { Loader2 } from 'lucide-svelte';
	import {
		Card,
		CardHeader,
		CardDescription,
		CardTitle,
		CardContent
	} from '$lib/components/ui/card';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import { Checkbox } from '$lib/components/ui/checkbox';
	import { Button } from '$lib/components/ui/button';
	import { toast } from 'svelte-sonner';

	import { authClient } from '$lib/auth-client';
	import { goto } from '$app/navigation';

	let loading = $state(false);

	const values = $state({
		email: '',
		password: '',
		rememberMe: false
	});

	async function handleSubmit(event: SubmitEvent) {
		event.preventDefault();

		loading = true;
		authClient.signIn
			.email({
				email: values.email,
				password: values.password,
				rememberMe: values.rememberMe
			})
			.then((data: any) => {
				if (data.data) {
					toast('Successfully Logged In');
					return goto('/');
				} else {
					toast(data.error.message);
				}
			})
			.catch(() => {
				toast('Error while signing in');
			})
			.finally(() => {
				loading = false;
			});
	}
</script>

<Card class="max-w-md">
	<CardHeader>
		<CardTitle class="text-lg md:text-xl">Sign In</CardTitle>

		<CardDescription class="text-xs md:text-sm">
			Enter your email below to login to your account
		</CardDescription>
	</CardHeader>

	<CardContent>
		<form onsubmit={handleSubmit} class="grid gap-4">
			<div class="grid gap-2">
				<Label for="email">Email</Label>

				<Input
					id="email"
					type="email"
					placeholder="m@example.com"
					required
					bind:value={values.email}
				/>
			</div>

			<div class="grid gap-2">
				<div class="flex items-center">
					<Label for="password">Password</Label>

					<a href="/" class="inline-block ml-auto text-sm underline"> Forgot your password? </a>
				</div>

				<Input
					id="password"
					type="password"
					placeholder="password"
					autocomplete="new-password"
					bind:value={values.password}
				/>
			</div>

			<div class="flex items-center gap-2">
				<Checkbox
					id="remember"
					checked={values.rememberMe}
					onCheckedChange={() => (values.rememberMe = !values.rememberMe)}
				/>

				<Label for="remember">Remember me</Label>
			</div>

			<Button type="submit" class="w-full" disabled={loading}>
				{#if loading}
					<Loader2 class="animate-spin" size="20" />
				{:else}
					Login
				{/if}
			</Button>

			<p>
				Don't have account ?
				<a href="/auth/register">Register</a>
			</p>
		</form>
	</CardContent>
</Card>

// hono-tanstack-hackernews/frontend/src/pages/(auth)/login.tsx
import {
  createFileRoute,
  Link,
  redirect,
  useNavigate,
  useRouter,
} from "@tanstack/react-router";
import { z } from "zod";
import { fallback, zodSearchValidator } from "@tanstack/router-zod-adapter";
import { useForm } from "@tanstack/react-form";
import { loginSchema } from "@/shared/types";
import { zodValidator } from "@tanstack/zod-form-adapter";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { FieldInfo } from "@/components/field-info";
import { Button } from "@/components/ui/button";
import { postLogin, userQueryOptions } from "@/lib/api";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";

const signupSearchSchema = z.object({
  redirect: fallback(z.string(), "/").default("/"),
});

export const Route = createFileRoute("/(auth)/login")({
  validateSearch: zodSearchValidator(signupSearchSchema),
  component: Login,
  beforeLoad: async ({ context, search }) => {
    const user = await context.queryClient.ensureQueryData(userQueryOptions());

    if (user) {
      throw redirect({ to: search.redirect });
    }
  },
});

function Login() {
  const search = Route.useSearch();
  const navigate = useNavigate();
  const router = useRouter();
  const queryClient = useQueryClient();

  const form = useForm({
    defaultValues: {
      username: "",
      password: "",
    },
    validatorAdapter: zodValidator(),
    validators: {
      onChange: loginSchema,
    },
    onSubmit: async ({ value }) => {
      const res = await postLogin(value.username, value.password);
      if (res.success) {
        await queryClient.invalidateQueries({ queryKey: ["user"] });
        router.invalidate();
        await navigate({ to: search.redirect });
        return null;
      } else {
        if (!res.isFormError) {
          toast.error("Signup failed", { description: res.error });
        }
        form.setErrorMap({
          onSubmit: res.isFormError ? res.error : "Unexpected error",
        });
      }
    },
  });

  return (
    <div className="size-full">
      <Card className="mx-auto mt-12 max-w-sm border-border/25">
        <form
          onSubmit={(e) => {
            e.preventDefault();
            e.stopPropagation();

            form.handleSubmit();
          }}
        >
          <CardHeader>
            <CardTitle className="text-center text-2xl">Login</CardTitle>
            <CardDescription className="text-center">
              Enter your details below to login
            </CardDescription>
          </CardHeader>

          <CardContent>
            <div className="grid gap-4">
              <form.Field
                name="username"
                children={(field) => (
                  <div className="grid gap-2">
                    <Label htmlFor={field.name}>Username</Label>
                    <Input
                      id={field.name}
                      name={field.name}
                      value={field.state.value}
                      onBlur={field.handleBlur}
                      onChange={(e) => field.handleChange(e.target.value)}
                      placeholder="Username"
                    />

                    <FieldInfo field={field} />
                  </div>
                )}
              />
              <form.Field
                name="password"
                children={(field) => (
                  <div className="grid gap-2">
                    <Label htmlFor={field.name}>Password</Label>
                    <Input
                      id={field.name}
                      name={field.name}
                      value={field.state.value}
                      onBlur={field.handleBlur}
                      onChange={(e) => field.handleChange(e.target.value)}
                      placeholder="******"
                    />

                    <FieldInfo field={field} />
                  </div>
                )}
              />

              <form.Subscribe
                selector={(state) => [state.errorMap]}
                children={([errorMap]) =>
                  errorMap.onSubmit ? (
                    <p className="text-[0.8rem] font-medium text-destructive">
                      {errorMap.onSubmit?.toString()}
                    </p>
                  ) : null
                }
              />

              <form.Subscribe
                selector={(state) => [state.canSubmit, state.isSubmitting]}
                children={([canSubmit, isSubmitting]) => (
                  <Button
                    type="submit"
                    disabled={!canSubmit}
                    className="w-full"
                  >
                    {isSubmitting ? "..." : "Login"}
                  </Button>
                )}
              />
            </div>
          </CardContent>

          <CardFooter>
            <p className="text-sm text-muted-foreground">
              {`Don't`} have an account ?{" "}
              <Link to="/signup" className="text-foreground hover:underline">
                SignUp
              </Link>
            </p>
          </CardFooter>
        </form>
      </Card>
    </div>
  );
}
